// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import {
  IsArray,
  IsBoolean,
  IsIn,
  IsNumber,
  IsObject,
  IsString,
} from 'class-validator';

/**
 * The Cloud Storage configuration where Cloud Functions archives should be uploaded.
 */
export class GoogleCloudFunctionsArtefactStorage {
  constructor(init: GoogleCloudFunctionsArtefactStorage) {
    Object.assign(this, init);
  }

  /**
   * The name of the Cloud Storage bucket.
   */
  @AllowMissing()
  @IsString()
  readonly bucket?: string;

  /**
   * An optional prefix within the Cloud Storage bucket.
   */
  @AllowMissing()
  @IsString()
  readonly prefix?: string;
  [property: string]: any;
}

/**
 * Configuration for Cloud Functions.
 */
export class GoogleCloudFunctions {
  constructor(init: GoogleCloudFunctions) {
    Object.assign(this, init);
  }

  /**
   * The Cloud Storage configuration where Cloud Functions archives should be uploaded.
   */
  @AllowMissing()
  readonly artefactStorage?: GoogleCloudFunctionsArtefactStorage;
  [property: string]: any;
}

/**
 * The type of allowed ingress that can reach the container.
 * See https://cloud.google.com/run/docs/securing/ingress#settings for more details.
 */
export enum GoogleCloudRunIngress {
  All = 'all',
  Internal = 'internal',
  InternalAndCloudLoadBalancing = 'internal-and-cloud-load-balancing',
}

/**
 * The setting for egress traffic that goes through the VPC access connector.
 * See https://cloud.google.com/run/docs/configuring/connecting-vpc#manage for more details.
 */
export enum GoogleCloudRunVpcAccessConnectorEgressSettings {
  AllTraffic = 'all-traffic',
  PrivateRangesOnly = 'private-ranges-only',
}

/**
 * Configuration for Cloud Run containers.
 */
export class GoogleCloudRun {
  constructor(init: GoogleCloudRun) {
    Object.assign(this, init);
  }

  /**
   * Whether the container is running between requests and can perform background operations.
   */
  @AllowMissing()
  @IsBoolean()
  readonly cpuAlwaysAllocated?: boolean;

  /**
   * The Docker repository where Cloud Run containers should be uploaded.
   */
  @AllowMissing()
  @IsString()
  readonly dockerRepository?: string;

  /**
   * The type of allowed ingress that can reach the container.
   * See https://cloud.google.com/run/docs/securing/ingress#settings for more details.
   */
  @AllowMissing()
  @IsIn(['all', 'internal', 'internal-and-cloud-load-balancing'])
  readonly ingress?: GoogleCloudRunIngress;

  /**
   * The location where Cloud Run services should be deployed.
   */
  @AllowMissing()
  @IsString()
  readonly location?: string;

  /**
   * The maximum allowed in-flight (concurrent) requests per container.
   */
  @AllowMissing()
  @IsNumber()
  readonly requestConcurrency?: number;

  /**
   * A map where keys are the name of environment variables, and values are secret versions IDs (e.g.
   * `projects/my-project/secrets/my-secret/versions/1`).
   */
  @AllowMissing()
  @IsObject()
  readonly secretEnvironmentVariables?: { [key: string]: string };

  /**
   * Whether to enable CPU boost during instance startup.
   */
  @AllowMissing()
  @IsBoolean()
  readonly startupCpuBoost?: boolean;

  /**
   * The max duration the instance is allowed for responding to a request, in seconds.
   */
  @AllowMissing()
  @IsNumber()
  readonly timeout?: number;

  /**
   * The name of the VPC access connector through which egress traffic should be routed.
   */
  @AllowMissing()
  @IsString()
  readonly vpcAccessConnector?: string;

  /**
   * The setting for egress traffic that goes through the VPC access connector.
   * See https://cloud.google.com/run/docs/configuring/connecting-vpc#manage for more details.
   */
  @AllowMissing()
  @IsIn(['all-traffic', 'private-ranges-only'])
  readonly vpcAccessConnectorEgressSettings?: GoogleCloudRunVpcAccessConnectorEgressSettings;
  [property: string]: any;
}

/**
 * Configuration for Firebase tools (the CLI).
 * This applies to Dockerized calls to the `firebase` CLI.
 */
export class GoogleFirebaseTools {
  constructor(init: GoogleFirebaseTools) {
    Object.assign(this, init);
  }

  /**
   * The version of the CLI to use.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;
  [property: string]: any;
}

/**
 * Configuration for the Firebase project.
 */
export class GoogleFirebase {
  constructor(init: GoogleFirebase) {
    Object.assign(this, init);
  }

  /**
   * An existing service account that can be used to sign Identity Platform custom token.
   * Generating custom tokens by signing them using end-user credentials does not work with Identity Platform.
   * A good choice is usually the service account automatically created by Firebase:
   * `firebase-adminsdk-<random ID>@<GCP project>.iam.gserviceaccount.com`
   * If this is not set and is needed by an operation, an attempt will be made to find this service account in the
   * current `google.project`.
   */
  @AllowMissing()
  @IsString()
  readonly adminServiceAccount?: string;

  /**
   * The Firebase API key used by clients. Used to perform requests to Firebase as an end user.
   * This can be found in the GCP or Firebase Console.
   * If this is not set and is needed by an operation, an attempt will be made to find the key automatically using
   * the API.
   */
  @AllowMissing()
  @IsString()
  readonly apiKey?: string;

  /**
   * The Firebase app ID used by clients.
   * This can be found in the Firebase Console. Each platform (Android, iOS, Web) has its own app ID.
   * If this is not set and is needed by an operation, an attempt will be made to find the first eligible app ID
   * using the Firebase API.
   */
  @AllowMissing()
  @IsString()
  readonly appId?: string;

  /**
   * The domain name for the project.
   * If not set, this default to `<GCP project>.firebaseapp.com`.
   */
  @AllowMissing()
  @IsString()
  readonly authDomain?: string;

  /**
   * Configuration for Firebase tools (the CLI).
   * This applies to Dockerized calls to the `firebase` CLI.
   */
  @AllowMissing()
  readonly tools?: GoogleFirebaseTools;
  [property: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleFirebaseStorageEmulator {
  constructor(init: GoogleFirebaseStorageEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;
  [property: string]: any;
}

/**
 * Configuration for the Firebase Storage service.
 */
export class GoogleFirebaseStorage {
  constructor(init: GoogleFirebaseStorage) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  readonly emulator?: GoogleFirebaseStorageEmulator;

  /**
   * The file path, relative to the workspace root, where the merged security rules file is written.
   */
  @AllowMissing()
  @IsString()
  readonly securityRuleFile?: string;

  /**
   * A list of glob patterns to find files in the workspace defining Firebase Storage security rules.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly securityRuleFiles?: string[];
  [property: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleFirestoreEmulator {
  constructor(init: GoogleFirestoreEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;
  [property: string]: any;
}

/**
 * Configuration for the Firestore service.
 */
export class GoogleFirestore {
  constructor(init: GoogleFirestore) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  readonly emulator?: GoogleFirestoreEmulator;

  /**
   * The file path, relative to the workspace root, where the merged security rules file is written.
   */
  @AllowMissing()
  @IsString()
  readonly securityRuleFile?: string;

  /**
   * A list of glob patterns to find files in the workspace defining Firestore security rules.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly securityRuleFiles?: string[];
  [property: string]: any;
}

/**
 * Configuration for the `gcloud` command.
 * This applies to Dockerized calls to `gcloud` using the official `gcloud` Docker image.
 */
export class GoogleGcloud {
  constructor(init: GoogleGcloud) {
    Object.assign(this, init);
  }

  /**
   * The version of the `gcloud` command.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;
  [property: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleIdentityPlatformEmulator {
  constructor(init: GoogleIdentityPlatformEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;
  [property: string]: any;
}

/**
 * Configuration for the Identity Platform (formerly Firebase Auth) service.
 */
export class GoogleIdentityPlatform {
  constructor(init: GoogleIdentityPlatform) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  readonly emulator?: GoogleIdentityPlatformEmulator;
  [property: string]: any;
}

/**
 * Configuration for Google Cloud load balancing.
 */
export class GoogleLoadBalancing {
  constructor(init: GoogleLoadBalancing) {
    Object.assign(this, init);
  }

  /**
   * A list of custom request headers to add to load-balanced requests.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly customRequestHeaders?: string[];
  [property: string]: any;
}

/**
 * Configuration for the storage of Pub/Sub events in BigQuery.
 */
export class GooglePubSubBigQueryStorage {
  constructor(init: GooglePubSubBigQueryStorage) {
    Object.assign(this, init);
  }

  /**
   * The BigQuery location for the datasets.
   * See https://cloud.google.com/bigquery/docs/locations for more details.
   */
  @AllowMissing()
  @IsString()
  readonly location?: string;

  /**
   * The ID of the BigQuery dataset where raw Pub/Sub events should be stored.
   */
  @AllowMissing()
  @IsString()
  readonly rawEventsDatasetId?: string;
  [property: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GooglePubSubEmulator {
  constructor(init: GooglePubSubEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;
  [property: string]: any;
}

/**
 * Configuration for the Pub/Sub service.
 */
export class GooglePubSub {
  constructor(init: GooglePubSub) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the storage of Pub/Sub events in BigQuery.
   */
  @AllowMissing()
  readonly bigQueryStorage?: GooglePubSubBigQueryStorage;

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  readonly emulator?: GooglePubSubEmulator;

  /**
   * The default maximum backoff for Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly maximumBackoff?: string;

  /**
   * The default minimum backoff for Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly minimumBackoff?: string;

  /**
   * The directory where the topic configuration files are written by the `GooglePubSubWriteTopics` processor.
   */
  @AllowMissing()
  @IsString()
  readonly topicConfigurationsDirectory?: string;
  [property: string]: any;
}

/**
 * Default configuration for Cloud Scheduler jobs.
 */
export class GoogleScheduler {
  constructor(init: GoogleScheduler) {
    Object.assign(this, init);
  }

  /**
   * The default deadline for Cloud Scheduler job attempts.
   */
  @AllowMissing()
  @IsString()
  readonly attemptDeadline?: string;

  /**
   * The default maximum backoff duration for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoffDuration?: string;

  /**
   * The default maximum number of times the backoff duration is doubled for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  /**
   * The default maximum duration for retrying a failed Cloud Scheduler job.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The default minimum backoff duration for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoffDuration?: string;

  /**
   * The default number of retry attempts for Cloud Scheduler jobs.
   */
  @AllowMissing()
  @IsNumber()
  readonly retryCount?: number;
  [property: string]: any;
}

/**
 * Configuration for the Secret Manager service.
 */
export class GoogleSecretManager {
  constructor(init: GoogleSecretManager) {
    Object.assign(this, init);
  }

  /**
   * The ID of the default GCP project referenced when fetching secrets.
   */
  @AllowMissing()
  @IsString()
  readonly project?: string;
  [property: string]: any;
}

/**
 * Defines how DDLs are found for the Spanner databases in the workspace.
 */
export class GoogleSpannerDdls {
  constructor(init: GoogleSpannerDdls) {
    Object.assign(this, init);
  }

  /**
   * The format string using groups from the regular expression used to make the database names.
   */
  @AllowMissing()
  @IsString()
  readonly format?: string;

  /**
   * A list of glob patterns used to find SQL files containing DDL statements for the Spanner databases.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * The regular expression used to extract groups from the SQL file paths.
   */
  @AllowMissing()
  @IsString()
  readonly regularExpression?: string;
  [property: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleSpannerEmulator {
  constructor(init: GoogleSpannerEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The name of the Spanner instance that will automatically be created in the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly instanceName?: string;

  /**
   * The version of the Spanner emulator Docker image to use.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;
  [property: string]: any;
}

/**
 * Autoscaling configuration for the Spanner instance.
 */
export class GoogleSpannerInstanceAutoscaling {
  constructor(init: GoogleSpannerInstanceAutoscaling) {
    Object.assign(this, init);
  }

  /**
   * The target high-priority CPU utilization percentage for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly highPriorityCpuUtilizationTarget?: number;

  /**
   * The maximum number of processing units for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxProcessingUnits?: number;

  /**
   * The minimum number of processing units for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly minProcessingUnits?: number;

  /**
   * The target storage utilization percentage for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly storageUtilizationTarget?: number;
  [property: string]: any;
}

/**
 * Configuration for the Spanner instance.
 */
export class GoogleSpannerInstance {
  constructor(init: GoogleSpannerInstance) {
    Object.assign(this, init);
  }

  /**
   * Autoscaling configuration for the Spanner instance.
   */
  @AllowMissing()
  readonly autoscaling?: GoogleSpannerInstanceAutoscaling;

  /**
   * The instance geographic configuration.
   * See https://cloud.google.com/spanner/docs/instance-configurations for more details.
   */
  @AllowMissing()
  @IsString()
  readonly configuration?: string;

  /**
   * The edition of the Spanner instance (e.g. STANDARD, ENTERPRISE).
   */
  @AllowMissing()
  @IsString()
  readonly edition?: string;

  /**
   * The name of the Spanner instance.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * The compute capacity of the instance.
   * See https://cloud.google.com/spanner/docs/compute-capacity for more details.
   */
  @AllowMissing()
  @IsNumber()
  readonly processingUnits?: number;
  [property: string]: any;
}

/**
 * Configuration for the Spanner service.
 */
export class GoogleSpanner {
  constructor(init: GoogleSpanner) {
    Object.assign(this, init);
  }

  /**
   * The directory where the database configuration files are written by the `GoogleSpannerWriteDatabases` processor.
   */
  @AllowMissing()
  @IsString()
  readonly databaseConfigurationsDirectory?: string;

  /**
   * The timeout for Spanner database DDL operations.
   */
  @AllowMissing()
  @IsString()
  readonly databaseDdlTimeout?: string;

  /**
   * Defines how DDLs are found for the Spanner databases in the workspace.
   */
  @AllowMissing()
  readonly ddls?: GoogleSpannerDdls;

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  readonly emulator?: GoogleSpannerEmulator;

  /**
   * Configuration for the Spanner instance.
   */
  @AllowMissing()
  readonly instance?: GoogleSpannerInstance;

  /**
   * The default version retention period for Spanner databases.
   */
  @AllowMissing()
  @IsString()
  readonly versionRetentionPeriod?: string;
  [property: string]: any;
}

/**
 * Configuration for everything Google / GCP-related.
 */
export class Google {
  constructor(init: Google) {
    Object.assign(this, init);
  }

  /**
   * Configuration for Cloud Functions.
   */
  @AllowMissing()
  readonly cloudFunctions?: GoogleCloudFunctions;

  /**
   * Configuration for Cloud Run containers.
   */
  @AllowMissing()
  readonly cloudRun?: GoogleCloudRun;

  /**
   * Configuration for the Firebase project.
   */
  @AllowMissing()
  readonly firebase?: GoogleFirebase;

  /**
   * Configuration for the Firebase Storage service.
   */
  @AllowMissing()
  readonly firebaseStorage?: GoogleFirebaseStorage;

  /**
   * Configuration for the Firestore service.
   */
  @AllowMissing()
  readonly firestore?: GoogleFirestore;

  /**
   * Configuration for the `gcloud` command.
   * This applies to Dockerized calls to `gcloud` using the official `gcloud` Docker image.
   */
  @AllowMissing()
  readonly gcloud?: GoogleGcloud;

  /**
   * Configuration for the Identity Platform (formerly Firebase Auth) service.
   */
  @AllowMissing()
  readonly identityPlatform?: GoogleIdentityPlatform;

  /**
   * Configuration for Google Cloud load balancing.
   */
  @AllowMissing()
  readonly loadBalancing?: GoogleLoadBalancing;

  /**
   * The ID of a local GCP project (which does not exist on GCP).
   * This is for example used by emulators. It should usually start with `demo-` to be compatible with some emulators.
   */
  @AllowMissing()
  @IsString()
  readonly localProject?: string;

  /**
   * The ID of the default GCP project used when performing operations.
   */
  @AllowMissing()
  @IsString()
  readonly project?: string;

  /**
   * Configuration for the Pub/Sub service.
   */
  @AllowMissing()
  readonly pubSub?: GooglePubSub;

  /**
   * The GCP region in which resource should be created and managed.
   */
  @AllowMissing()
  @IsString()
  readonly region?: string;

  /**
   * Default configuration for Cloud Scheduler jobs.
   */
  @AllowMissing()
  readonly scheduler?: GoogleScheduler;

  /**
   * Configuration for the Secret Manager service.
   */
  @AllowMissing()
  readonly secretManager?: GoogleSecretManager;

  /**
   * The list of GCP services on which the project depends.
   * This is useful to automatically enable those services in the GCP project.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly services?: string[];

  /**
   * Configuration for the Spanner service.
   */
  @AllowMissing()
  readonly spanner?: GoogleSpanner;
  [property: string]: any;
}

/**
 * The schema for Google / GCP configuration.
 */
export class GoogleConfiguration {
  constructor(init: GoogleConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for everything Google / GCP-related.
   */
  @AllowMissing()
  readonly google?: Google;
  [property: string]: any;
}

export class Outputs {
  constructor(init: Outputs) {
    Object.assign(this, init);
  }

  /**
   * The list of Firestore collections this service produces data into.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly 'google.firestore'?: string[];

  /**
   * The list of Spanner databases this service produces data into.
   * Each entry should be in the format `instance.database`.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly 'google.spanner'?: string[];
  [property: string]: any;
}

export class ServiceContainerGoogleEventarcTriggerFilter {
  constructor(init: ServiceContainerGoogleEventarcTriggerFilter) {
    Object.assign(this, init);
  }

  /**
   * The event attribute to filter on.
   */
  @IsString()
  readonly attribute!: string;

  /**
   * The operator for matching the filter.
   */
  @AllowMissing()
  @IsString()
  readonly operator?: string;

  /**
   * The value to match for the attribute.
   */
  @IsString()
  readonly value!: string;
  [property: string]: any;
}

/**
 * Google Eventarc-specific options for the trigger.
 */
export class ServiceContainerGoogleEventarcTriggerOptions {
  constructor(init: ServiceContainerGoogleEventarcTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * The content type of event data.
   */
  @IsString()
  readonly contentType!: string;

  /**
   * The list of matching criteria for the Eventarc trigger.
   */
  @IsArray()
  readonly filters!: ServiceContainerGoogleEventarcTriggerFilter[];

  /**
   * The location of the Eventarc trigger.
   */
  @AllowMissing()
  @IsString()
  readonly location?: string;
  [property: string]: any;
}

/**
 * Google Pub/Sub-specific options for the trigger.
 */
export class ServiceContainerGooglePubSubTriggerOptions {
  constructor(init: ServiceContainerGooglePubSubTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * A Pub/Sub filter expression for the subscription.
   */
  @AllowMissing()
  @IsString()
  readonly filter?: string;

  /**
   * The maximum backoff for the Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly maximumBackoff?: string;

  /**
   * The minimum backoff for the Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly minimumBackoff?: string;
  [property: string]: any;
}

/**
 * Google Cloud Scheduler-specific options for the trigger.
 */
export class ServiceContainerGoogleSchedulerTriggerOptions {
  constructor(init: ServiceContainerGoogleSchedulerTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * The deadline for job attempts.
   */
  @AllowMissing()
  @IsString()
  readonly attemptDeadline?: string;

  /**
   * The maximum backoff duration for job retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoffDuration?: string;

  /**
   * The maximum number of times the backoff duration is doubled.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  /**
   * The maximum duration for retrying a failed job.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The minimum backoff duration for job retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoffDuration?: string;

  /**
   * The number of retry attempts for the Cloud Scheduler job.
   */
  @AllowMissing()
  @IsNumber()
  readonly retryCount?: number;
  [property: string]: any;
}

/**
 * The retry policy for the Cloud Tasks queue.
 */
export class ServiceContainerGoogleTaskTriggerRetryPolicy {
  constructor(init: ServiceContainerGoogleTaskTriggerRetryPolicy) {
    Object.assign(this, init);
  }

  /**
   * The maximum number of attempts for a task.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxAttempts?: number;

  /**
   * The maximum backoff duration for task retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoff?: string;

  /**
   * The maximum number of times the backoff duration is doubled.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  /**
   * The maximum duration for retrying a failed task.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The minimum backoff duration for task retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoff?: string;
  [property: string]: any;
}

/**
 * A trigger backed by a Google Eventarc trigger.
 */
export class ServiceContainerGoogleTrigger {
  constructor(init: ServiceContainerGoogleTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsString()
  readonly type!: string;

  /**
   * Google Pub/Sub-specific options for the trigger.
   */
  @AllowMissing()
  readonly 'google.pubSub'?: ServiceContainerGooglePubSubTriggerOptions;

  /**
   * The ID of the topic triggering the endpoint.
   */
  @AllowMissing()
  @IsString()
  readonly topic?: string;

  /**
   * Google Cloud Scheduler-specific options for the trigger.
   */
  @AllowMissing()
  readonly 'google.scheduler'?: ServiceContainerGoogleSchedulerTriggerOptions;

  /**
   * The cron schedule expression for cron triggers.
   */
  @AllowMissing()
  @IsString()
  readonly schedule?: string;

  /**
   * The timezone for the cron schedule.
   */
  @AllowMissing()
  @IsString()
  readonly timezone?: string;

  /**
   * The name of the queue for task triggers.
   */
  @AllowMissing()
  @IsString()
  readonly queue?: string;

  /**
   * The retry policy for the Cloud Tasks queue.
   */
  @AllowMissing()
  readonly retryPolicy?: ServiceContainerGoogleTaskTriggerRetryPolicy;

  /**
   * Google Eventarc-specific options for the trigger.
   */
  @AllowMissing()
  readonly 'google.eventarc'?: ServiceContainerGoogleEventarcTriggerOptions;
  [property: string]: any;
}

export class ServiceContainer {
  constructor(init: ServiceContainer) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly outputs?: Outputs;

  /**
   * A map of triggers that call the service's endpoints when they occur.
   */
  @AllowMissing()
  @IsObject()
  readonly triggers?: { [key: string]: ServiceContainerGoogleTrigger };
  [property: string]: any;
}

/**
 * Google-specific extensions to the service container configuration.
 */
export class GoogleServiceContainerConfiguration {
  constructor(init: GoogleServiceContainerConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly serviceContainer?: ServiceContainer;
  [property: string]: any;
}
