// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import {
  Allow,
  IsArray,
  IsBoolean,
  IsDefined,
  IsIn,
  IsNumber,
  IsObject,
  IsString,
  ValidateNested,
} from 'class-validator';

export enum GoogleAccessTokenSecretConfigurationBackend {
  GoogleAccessToken = 'google.accessToken',
}

/**
 * A secret that returns a Google access token for the current user or service account.
 * This backend does not require any additional configuration.
 */
export class GoogleAccessTokenSecretConfiguration {
  constructor(init: GoogleAccessTokenSecretConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsIn(['google.accessToken'])
  readonly backend?: GoogleAccessTokenSecretConfigurationBackend;

  [key: string]: any;
}

/**
 * The Cloud Storage configuration where Cloud Functions archives should be uploaded.
 */
export class GoogleCloudFunctionsArtefactStorage {
  constructor(init: GoogleCloudFunctionsArtefactStorage) {
    Object.assign(this, init);
  }

  /**
   * The name of the Cloud Storage bucket.
   */
  @AllowMissing()
  @IsString()
  readonly bucket?: string;

  /**
   * An optional prefix within the Cloud Storage bucket.
   */
  @AllowMissing()
  @IsString()
  readonly prefix?: string;

  [key: string]: any;
}

/**
 * Configuration for Cloud Functions.
 */
export class GoogleCloudFunctions {
  constructor(init: GoogleCloudFunctions) {
    Object.assign(this, init);
  }

  /**
   * The Cloud Storage configuration where Cloud Functions archives should be uploaded.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleCloudFunctionsArtefactStorage)
  @ValidateNested()
  readonly artefactStorage?: GoogleCloudFunctionsArtefactStorage;

  [key: string]: any;
}

/**
 * Google Cloud Functions platform.
 */
export enum GoogleCloudFunctionsPlatform {
  GoogleCloudFunctions = 'google.cloudFunctions',
}

/**
 * When set, project-scoped backfill triggers do not send events to the live Cloud Run service. Instead, a
 * temporary copy of the service is deployed for each trigger, isolating the backfill load (in particular its
 * scaling) from production. The copy is deleted once the backfill is cleaned up. Ingress is always
 * restricted to internal traffic for the copy. The properties of this object override the scaling settings
 * of the copied service. Unset properties are inherited from the live service.
 */
export class GoogleCloudRunEventBackfillServiceCloneConfig {
  constructor(init: GoogleCloudRunEventBackfillServiceCloneConfig) {
    Object.assign(this, init);
  }

  /**
   * The minimum number of instances for the temporary service copy.
   */
  @AllowMissing()
  @IsNumber()
  readonly minInstanceCount?: number;

  /**
   * The maximum number of instances for the temporary service copy.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxInstanceCount?: number;

  /**
   * The maximum number of concurrent requests per instance for the temporary service copy.
   */
  @AllowMissing()
  @IsNumber()
  readonly requestConcurrency?: number;

  [key: string]: any;
}

/**
 * The type of allowed ingress that can reach the container.
 * See https://cloud.google.com/run/docs/securing/ingress#settings for more details.
 */
export enum GoogleCloudRunIngress {
  All = 'all',
  Internal = 'internal',
  InternalAndCloudLoadBalancing = 'internal-and-cloud-load-balancing',
}

/**
 * Google Cloud Run platform.
 */
export enum GoogleCloudRunPlatform {
  GoogleCloudRun = 'google.cloudRun',
}

/**
 * The setting for egress traffic that goes through the VPC access connector.
 * See https://cloud.google.com/run/docs/configuring/connecting-vpc#manage for more details.
 */
export enum GoogleCloudRunVpcAccessConnectorEgressSettings {
  AllTraffic = 'ALL_TRAFFIC',
  PrivateRangesOnly = 'PRIVATE_RANGES_ONLY',
}

/**
 * Configuration for the emulator.
 */
export class GoogleFirebaseStorageEmulator {
  constructor(init: GoogleFirebaseStorageEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The host port to which the Firebase Storage emulator is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `9199`.
   */
  @AllowMissing()
  @IsNumber()
  readonly port?: number;

  [key: string]: any;
}

/**
 * Configuration for the Firebase Storage service.
 */
export class GoogleFirebaseStorage {
  constructor(init: GoogleFirebaseStorage) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirebaseStorageEmulator)
  @ValidateNested()
  readonly emulator?: GoogleFirebaseStorageEmulator;

  /**
   * A list of glob patterns to find files in the workspace defining Firebase Storage security rules.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly securityRuleFiles?: string[];

  /**
   * The file path, relative to the workspace root, where the merged security rules file is written.
   */
  @AllowMissing()
  @IsString()
  readonly securityRuleFile?: string;

  [key: string]: any;
}

export enum GoogleFirebaseStorageMergeRulesProcessorName {
  GoogleFirebaseStorageMergeRules = 'GoogleFirebaseStorageMergeRules',
}

/**
 * Merges all Firebase Storage security rules from the workspace.
 * Sets the `google.firebaseStorage.securityRuleFile` configuration value.
 */
export class GoogleFirebaseStorageMergeRulesProcessor {
  constructor(init: GoogleFirebaseStorageMergeRulesProcessor) {
    Object.assign(this, init);
  }

  @IsIn(['GoogleFirebaseStorageMergeRules'])
  readonly name!: GoogleFirebaseStorageMergeRulesProcessorName;

  [key: string]: any;
}

/**
 * Configuration for Firebase tools (the CLI).
 * This applies to Dockerized calls to the `firebase` CLI.
 */
export class GoogleFirebaseTools {
  constructor(init: GoogleFirebaseTools) {
    Object.assign(this, init);
  }

  /**
   * The version of the CLI to use.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  [key: string]: any;
}

/**
 * Configuration for the Firebase project.
 */
export class GoogleFirebase {
  constructor(init: GoogleFirebase) {
    Object.assign(this, init);
  }

  /**
   * An existing service account that can be used to sign Identity Platform custom token.
   * Generating custom tokens by signing them using end-user credentials does not work with Identity Platform.
   * A good choice is usually the service account automatically created by Firebase:
   * `firebase-adminsdk-<random ID>@<GCP project>.iam.gserviceaccount.com`
   * If this is not set and is needed by an operation, an attempt will be made to find this service account in the
   * current `google.project`.
   */
  @AllowMissing()
  @IsString()
  readonly adminServiceAccount?: string;

  /**
   * The Firebase API key used by clients. Used to perform requests to Firebase as an end user.
   * This can be found in the GCP or Firebase Console.
   * If this is not set and is needed by an operation, an attempt will be made to find the key automatically using
   * the API.
   */
  @AllowMissing()
  @IsString()
  readonly apiKey?: string;

  /**
   * The Firebase app ID used by clients.
   * This can be found in the Firebase Console. Each platform (Android, iOS, Web) has its own app ID.
   * If this is not set and is needed by an operation, an attempt will be made to find the first eligible app ID
   * using the Firebase API.
   */
  @AllowMissing()
  @IsString()
  readonly appId?: string;

  /**
   * The domain name for the project.
   * If not set, this default to `<GCP project>.firebaseapp.com`.
   */
  @AllowMissing()
  @IsString()
  readonly authDomain?: string;

  /**
   * Configuration for Firebase tools (the CLI).
   * This applies to Dockerized calls to the `firebase` CLI.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirebaseTools)
  @ValidateNested()
  readonly tools?: GoogleFirebaseTools;

  [key: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleFirestoreEmulator {
  constructor(init: GoogleFirestoreEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The host port to which the Firestore emulator is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `8080`.
   */
  @AllowMissing()
  @IsNumber()
  readonly port?: number;

  [key: string]: any;
}

/**
 * Configuration for the Firestore service.
 */
export class GoogleFirestore {
  constructor(init: GoogleFirestore) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirestoreEmulator)
  @ValidateNested()
  readonly emulator?: GoogleFirestoreEmulator;

  /**
   * A list of glob patterns to find files in the workspace defining Firestore security rules.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly securityRuleFiles?: string[];

  /**
   * The file path, relative to the workspace root, where the merged security rules file is written.
   */
  @AllowMissing()
  @IsString()
  readonly securityRuleFile?: string;

  [key: string]: any;
}

export enum GoogleFirestoreMergeRulesProcessorName {
  GoogleFirestoreMergeRules = 'GoogleFirestoreMergeRules',
}

/**
 * Merges all Firestore security rules from the workspace.
 * Sets the `google.firestore.securityRuleFile` configuration value.
 */
export class GoogleFirestoreMergeRulesProcessor {
  constructor(init: GoogleFirestoreMergeRulesProcessor) {
    Object.assign(this, init);
  }

  @IsIn(['GoogleFirestoreMergeRules'])
  readonly name!: GoogleFirestoreMergeRulesProcessorName;

  [key: string]: any;
}

/**
 * Configuration for the `gcloud` command.
 * This applies to Dockerized calls to `gcloud` using the official `gcloud` Docker image.
 */
export class GoogleGcloud {
  constructor(init: GoogleGcloud) {
    Object.assign(this, init);
  }

  /**
   * The version of the `gcloud` command.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  [key: string]: any;
}

export class GoogleGenericProcessor {
  constructor(init: GoogleGenericProcessor) {
    Object.assign(this, init);
  }

  @IsString()
  readonly name!: string;

  [key: string]: any;
}

export class GoogleGenericSecretConfiguration {
  constructor(init: GoogleGenericSecretConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsString()
  readonly backend?: string;

  [key: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleIdentityPlatformEmulator {
  constructor(init: GoogleIdentityPlatformEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The host port to which the Identity Platform (Firebase Auth) emulator is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `9099`.
   */
  @AllowMissing()
  @IsNumber()
  readonly port?: number;

  [key: string]: any;
}

/**
 * Configuration for the Identity Platform (formerly Firebase Auth) service.
 */
export class GoogleIdentityPlatform {
  constructor(init: GoogleIdentityPlatform) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleIdentityPlatformEmulator)
  @ValidateNested()
  readonly emulator?: GoogleIdentityPlatformEmulator;

  [key: string]: any;
}

/**
 * Configuration for Google Cloud load balancing.
 */
export class GoogleLoadBalancing {
  constructor(init: GoogleLoadBalancing) {
    Object.assign(this, init);
  }

  /**
   * A list of custom request headers to add to load-balanced requests.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly customRequestHeaders?: string[];

  [key: string]: any;
}

/**
 * Options when publishing events in batches to Pub/Sub during a backfill.
 */
export class GooglePubSubBackfillPublishOptions {
  constructor(init: GooglePubSubBackfillPublishOptions) {
    Object.assign(this, init);
  }

  /**
   * The maximum number of bytes allowed in outstanding (in-flight) publish requests before applying flow control.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxOutstandingBytes?: number;

  /**
   * The maximum number of outstanding (in-flight) messages allowed before applying flow control.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxOutstandingMessages?: number;

  /**
   * The maximum number of bytes to buffer before publishing a batch.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxBytes?: number;

  /**
   * The maximum number of messages to buffer before publishing a batch.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxMessages?: number;

  /**
   * The maximum duration to wait, in milliseconds, before publishing a batch.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxMilliseconds?: number;

  [key: string]: any;
}

/**
 * Configuration for the storage of Pub/Sub events in BigQuery.
 */
export class GooglePubSubBigQueryStorage {
  constructor(init: GooglePubSubBigQueryStorage) {
    Object.assign(this, init);
  }

  /**
   * The ID of the BigQuery dataset where raw Pub/Sub events should be stored.
   */
  @AllowMissing()
  @IsString()
  readonly rawEventsDatasetId?: string;

  /**
   * The BigQuery location for the datasets.
   * See https://cloud.google.com/bigquery/docs/locations for more details.
   */
  @AllowMissing()
  @IsString()
  readonly location?: string;

  [key: string]: any;
}

/**
 * Google Pub/Sub message broker.
 */
export enum GooglePubSubBroker {
  GooglePubSub = 'google.pubSub',
}

export type GoogleEventsBroker = string | GooglePubSubBroker;

export class GoogleEvents {
  constructor(init: GoogleEvents) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly broker?: GoogleEventsBroker;

  [key: string]: any;
}

/**
 * Google-specific refinement of the events configuration.
 */
export class GoogleEventsConfiguration {
  constructor(init: GoogleEventsConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleEvents)
  @ValidateNested()
  readonly events?: GoogleEvents;

  [key: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GooglePubSubEmulator {
  constructor(init: GooglePubSubEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The host port to which the Pub/Sub emulator is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `8085`.
   */
  @AllowMissing()
  @IsNumber()
  readonly port?: number;

  [key: string]: any;
}

/**
 * Configuration for the Pub/Sub service.
 */
export class GooglePubSub {
  constructor(init: GooglePubSub) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GooglePubSubEmulator)
  @ValidateNested()
  readonly emulator?: GooglePubSubEmulator;

  /**
   * The directory where the topic configuration files are written by the `GooglePubSubWriteTopics` processor.
   */
  @AllowMissing()
  @IsString()
  readonly topicConfigurationsDirectory?: string;

  /**
   * The default minimum backoff for Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly minimumBackoff?: string;

  /**
   * The default maximum backoff for Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly maximumBackoff?: string;

  /**
   * Configuration for the storage of Pub/Sub events in BigQuery.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GooglePubSubBigQueryStorage)
  @ValidateNested()
  readonly bigQueryStorage?: GooglePubSubBigQueryStorage;

  /**
   * Options when publishing events in batches to Pub/Sub during a backfill.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GooglePubSubBackfillPublishOptions)
  @ValidateNested()
  readonly backfillPublishOptions?: GooglePubSubBackfillPublishOptions;

  [key: string]: any;
}

export enum GooglePubSubWriteTopicsProcessorName {
  GooglePubSubWriteTopics = 'GooglePubSubWriteTopics',
}

/**
 * Writes Pub/Sub topic configurations to JSON files.
 * Sets the `google.pubSub.topicConfigurationsDirectory` configuration value.
 */
export class GooglePubSubWriteTopicsProcessor {
  constructor(init: GooglePubSubWriteTopicsProcessor) {
    Object.assign(this, init);
  }

  @IsIn(['GooglePubSubWriteTopics'])
  readonly name!: GooglePubSubWriteTopicsProcessorName;

  [key: string]: any;
}

/**
 * Default configuration for Cloud Scheduler jobs.
 */
export class GoogleScheduler {
  constructor(init: GoogleScheduler) {
    Object.assign(this, init);
  }

  /**
   * The default number of retry attempts for Cloud Scheduler jobs.
   */
  @AllowMissing()
  @IsNumber()
  readonly retryCount?: number;

  /**
   * The default maximum duration for retrying a failed Cloud Scheduler job.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The default minimum backoff duration for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoffDuration?: string;

  /**
   * The default maximum backoff duration for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoffDuration?: string;

  /**
   * The default maximum number of times the backoff duration is doubled for Cloud Scheduler job retries.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  /**
   * The default deadline for Cloud Scheduler job attempts.
   */
  @AllowMissing()
  @IsString()
  readonly attemptDeadline?: string;

  [key: string]: any;
}

/**
 * Configuration for the Secret Manager service.
 */
export class GoogleSecretManager {
  constructor(init: GoogleSecretManager) {
    Object.assign(this, init);
  }

  /**
   * The ID of the default GCP project referenced when fetching secrets.
   */
  @AllowMissing()
  @IsString()
  readonly project?: string;

  [key: string]: any;
}

/**
 * Google Secret Manager backend.
 */
export enum GoogleSecretManagerBackend {
  GoogleSecretManager = 'google.secretManager',
}

export enum GoogleSecretManagerSecretConfigurationBackend {
  GoogleSecretManager = 'google.secretManager',
}

/**
 * A secret stored in Google Secret Manager.
 */
export class GoogleSecretManagerSecretConfiguration {
  constructor(init: GoogleSecretManagerSecretConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsIn(['google.secretManager'])
  readonly backend?: GoogleSecretManagerSecretConfigurationBackend;

  /**
   * The reference to the secret in Google Secret Manager.
   * Supported formats: `<secret-name>`, `projects/<project>/secrets/<secret-name>`, `projects/<project>/secrets/<secret-name>/versions/<version>`.
   * If the project is not specified, `google.secretManager.project` or `google.project` will be used.
   * If the version is not specified, `latest` will be used.
   */
  @AllowMissing()
  @IsString()
  readonly id?: string;

  [key: string]: any;
}

export type GoogleSecretConfiguration =
  | GoogleGenericSecretConfiguration
  | GoogleSecretManagerSecretConfiguration
  | GoogleAccessTokenSecretConfiguration;

export type GoogleSecretsDefaultBackend = string | GoogleSecretManagerBackend;

export class GoogleSecretsCausaSecrets {
  constructor(init: GoogleSecretsCausaSecrets) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly defaultBackend?: GoogleSecretsDefaultBackend;

  [key: string]: any;
}

export class GoogleSecretsCausa {
  constructor(init: GoogleSecretsCausa) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSecretsCausaSecrets)
  @ValidateNested()
  readonly secrets?: GoogleSecretsCausaSecrets;

  [key: string]: any;
}

/**
 * Google-specific refinement of the secrets configuration.
 */
export class GoogleSecretsConfiguration {
  constructor(init: GoogleSecretsConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSecretsCausa)
  @ValidateNested()
  readonly causa?: GoogleSecretsCausa;

  @AllowMissing()
  @IsObject()
  readonly secrets?: Record<string, GoogleSecretConfiguration>;

  [key: string]: any;
}

export type GoogleServerlessFunctionsPlatform =
  | string
  | GoogleCloudFunctionsPlatform;

export class GoogleServerlessFunctions {
  constructor(init: GoogleServerlessFunctions) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly platform?: GoogleServerlessFunctionsPlatform;

  [key: string]: any;
}

/**
 * Google-specific refinement of the serverless functions configuration.
 */
export class GoogleServerlessFunctionsConfiguration {
  constructor(init: GoogleServerlessFunctionsConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleServerlessFunctions)
  @ValidateNested()
  readonly serverlessFunctions?: GoogleServerlessFunctions;

  [key: string]: any;
}

export enum GoogleServicesEnableProcessorName {
  GoogleServicesEnable = 'GoogleServicesEnable',
}

/**
 * Enables GCP services defined in the `google.services` configuration.
 */
export class GoogleServicesEnableProcessor {
  constructor(init: GoogleServicesEnableProcessor) {
    Object.assign(this, init);
  }

  @IsIn(['GoogleServicesEnable'])
  readonly name!: GoogleServicesEnableProcessorName;

  [key: string]: any;
}

/**
 * Defines how DDLs are found for the Spanner databases in the workspace.
 */
export class GoogleSpannerDdls {
  constructor(init: GoogleSpannerDdls) {
    Object.assign(this, init);
  }

  /**
   * The format string using groups from the regular expression used to make the database names.
   */
  @AllowMissing()
  @IsString()
  readonly format?: string;

  /**
   * A list of glob patterns used to find SQL files containing DDL statements for the Spanner databases.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * The regular expression used to extract groups from the SQL file paths.
   */
  @AllowMissing()
  @IsString()
  readonly regularExpression?: string;

  [key: string]: any;
}

/**
 * Configuration for the emulator.
 */
export class GoogleSpannerEmulator {
  constructor(init: GoogleSpannerEmulator) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker container running the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly containerName?: string;

  /**
   * The version of the Spanner emulator Docker image to use.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  /**
   * The name of the Spanner instance that will automatically be created in the emulator.
   */
  @AllowMissing()
  @IsString()
  readonly instanceName?: string;

  /**
   * The host port to which the Spanner emulator gRPC API is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `9010`.
   */
  @AllowMissing()
  @IsNumber()
  readonly grpcPort?: number;

  /**
   * The host port to which the Spanner emulator HTTP API is bound.
   * Override this to run several workspaces in parallel on the same machine. Defaults to `9020`.
   */
  @AllowMissing()
  @IsNumber()
  readonly httpPort?: number;

  [key: string]: any;
}

/**
 * Autoscaling configuration for the Spanner instance.
 */
export class GoogleSpannerInstanceAutoscaling {
  constructor(init: GoogleSpannerInstanceAutoscaling) {
    Object.assign(this, init);
  }

  /**
   * The maximum number of processing units for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxProcessingUnits?: number;

  /**
   * The minimum number of processing units for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly minProcessingUnits?: number;

  /**
   * The target high-priority CPU utilization percentage for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly highPriorityCpuUtilizationTarget?: number;

  /**
   * The target storage utilization percentage for autoscaling.
   */
  @AllowMissing()
  @IsNumber()
  readonly storageUtilizationTarget?: number;

  [key: string]: any;
}

/**
 * Configuration for the Spanner instance.
 */
export class GoogleSpannerInstance {
  constructor(init: GoogleSpannerInstance) {
    Object.assign(this, init);
  }

  /**
   * The name of the Spanner instance.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * The instance geographic configuration.
   * See https://cloud.google.com/spanner/docs/instance-configurations for more details.
   */
  @AllowMissing()
  @IsString()
  readonly configuration?: string;

  /**
   * The compute capacity of the instance.
   * See https://cloud.google.com/spanner/docs/compute-capacity for more details.
   */
  @AllowMissing()
  @IsNumber()
  readonly processingUnits?: number;

  /**
   * Autoscaling configuration for the Spanner instance.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSpannerInstanceAutoscaling)
  @ValidateNested()
  readonly autoscaling?: GoogleSpannerInstanceAutoscaling;

  /**
   * The edition of the Spanner instance (e.g. STANDARD, ENTERPRISE).
   */
  @AllowMissing()
  @IsString()
  readonly edition?: string;

  [key: string]: any;
}

/**
 * Configuration for the Spanner service.
 */
export class GoogleSpanner {
  constructor(init: GoogleSpanner) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the emulator.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSpannerEmulator)
  @ValidateNested()
  readonly emulator?: GoogleSpannerEmulator;

  /**
   * Configuration for the Spanner instance.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSpannerInstance)
  @ValidateNested()
  readonly instance?: GoogleSpannerInstance;

  /**
   * Defines how DDLs are found for the Spanner databases in the workspace.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSpannerDdls)
  @ValidateNested()
  readonly ddls?: GoogleSpannerDdls;

  /**
   * The directory where the database configuration files are written by the `GoogleSpannerWriteDatabases` processor.
   */
  @AllowMissing()
  @IsString()
  readonly databaseConfigurationsDirectory?: string;

  /**
   * The default version retention period for Spanner databases.
   */
  @AllowMissing()
  @IsString()
  readonly versionRetentionPeriod?: string;

  /**
   * The timeout for Spanner database DDL operations.
   */
  @AllowMissing()
  @IsString()
  readonly databaseDdlTimeout?: string;

  [key: string]: any;
}

export enum GoogleSpannerWriteDatabasesProcessorName {
  GoogleSpannerWriteDatabases = 'GoogleSpannerWriteDatabases',
}

/**
 * Writes Spanner database configurations to JSON files.
 * Sets the `google.spanner.databaseConfigurationsDirectory` configuration value.
 */
export class GoogleSpannerWriteDatabasesProcessor {
  constructor(init: GoogleSpannerWriteDatabasesProcessor) {
    Object.assign(this, init);
  }

  @IsIn(['GoogleSpannerWriteDatabases'])
  readonly name!: GoogleSpannerWriteDatabasesProcessorName;

  [key: string]: any;
}

export type GoogleInfrastructureProcessor =
  | GoogleGenericProcessor
  | GoogleServicesEnableProcessor
  | GooglePubSubWriteTopicsProcessor
  | GoogleSpannerWriteDatabasesProcessor
  | GoogleFirestoreMergeRulesProcessor
  | GoogleFirebaseStorageMergeRulesProcessor;

export class GoogleInfrastructure {
  constructor(init: GoogleInfrastructure) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsArray()
  readonly processors?: GoogleInfrastructureProcessor[];

  [key: string]: any;
}

/**
 * Google-specific refinement of the infrastructure configuration with known processors.
 */
export class GoogleInfrastructureConfiguration {
  constructor(init: GoogleInfrastructureConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleInfrastructure)
  @ValidateNested()
  readonly infrastructure?: GoogleInfrastructure;

  [key: string]: any;
}

export class ServiceContainerGenericTrigger {
  constructor(init: ServiceContainerGenericTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsString()
  readonly type!: string;

  [key: string]: any;
}

/**
 * The type of trigger.
 */
export enum ServiceContainerGoogleEventarcTriggerType {
  GoogleEventarc = 'google.eventarc',
}

/**
 * Google Pub/Sub-specific options for the trigger.
 */
export class ServiceContainerGooglePubSubTriggerOptions {
  constructor(init: ServiceContainerGooglePubSubTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * The minimum backoff for the Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly minimumBackoff?: string;

  /**
   * The maximum backoff for the Pub/Sub push subscription retry policy.
   */
  @AllowMissing()
  @IsString()
  readonly maximumBackoff?: string;

  /**
   * A Pub/Sub filter expression for the subscription.
   */
  @AllowMissing()
  @IsString()
  readonly filter?: string;

  [key: string]: any;
}

/**
 * The type of trigger.
 */
export enum ServiceContainerGooglePubSubTriggerType {
  GooglePubSub = 'google.pubSub',
  Event = 'event',
}

/**
 * A trigger backed by a Google Pub/Sub subscription.
 */
export class ServiceContainerGooglePubSubTrigger {
  constructor(init: ServiceContainerGooglePubSubTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsIn(['google.pubSub', 'event'])
  readonly type!: ServiceContainerGooglePubSubTriggerType;

  /**
   * The ID of the topic triggering the endpoint.
   */
  @IsString()
  readonly topic!: string;

  /**
   * Google Pub/Sub-specific options for the trigger.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerGooglePubSubTriggerOptions)
  @ValidateNested()
  readonly 'google.pubSub'?: ServiceContainerGooglePubSubTriggerOptions;

  [key: string]: any;
}

/**
 * Google Cloud Scheduler-specific options for the trigger.
 */
export class ServiceContainerGoogleSchedulerTriggerOptions {
  constructor(init: ServiceContainerGoogleSchedulerTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * The number of retry attempts for the Cloud Scheduler job.
   */
  @AllowMissing()
  @IsNumber()
  readonly retryCount?: number;

  /**
   * The maximum duration for retrying a failed job.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The minimum backoff duration for job retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoffDuration?: string;

  /**
   * The maximum backoff duration for job retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoffDuration?: string;

  /**
   * The maximum number of times the backoff duration is doubled.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  /**
   * The deadline for job attempts.
   */
  @AllowMissing()
  @IsString()
  readonly attemptDeadline?: string;

  [key: string]: any;
}

/**
 * The type of trigger.
 */
export enum ServiceContainerGoogleSchedulerTriggerType {
  GoogleScheduler = 'google.scheduler',
  Cron = 'cron',
}

/**
 * A trigger backed by a Google Cloud Scheduler job.
 */
export class ServiceContainerGoogleSchedulerTrigger {
  constructor(init: ServiceContainerGoogleSchedulerTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsIn(['google.scheduler', 'cron'])
  readonly type!: ServiceContainerGoogleSchedulerTriggerType;

  /**
   * The cron schedule expression for cron triggers.
   */
  @IsString()
  readonly schedule!: string;

  /**
   * The timezone for the cron schedule.
   */
  @AllowMissing()
  @IsString()
  readonly timezone?: string;

  /**
   * Google Cloud Scheduler-specific options for the trigger.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerGoogleSchedulerTriggerOptions)
  @ValidateNested()
  readonly 'google.scheduler'?: ServiceContainerGoogleSchedulerTriggerOptions;

  [key: string]: any;
}

/**
 * The retry policy for the Cloud Tasks queue.
 */
export class ServiceContainerGoogleTaskTriggerRetryPolicy {
  constructor(init: ServiceContainerGoogleTaskTriggerRetryPolicy) {
    Object.assign(this, init);
  }

  /**
   * The maximum number of attempts for a task.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxAttempts?: number;

  /**
   * The maximum duration for retrying a failed task.
   */
  @AllowMissing()
  @IsString()
  readonly maxRetryDuration?: string;

  /**
   * The minimum backoff duration for task retries.
   */
  @AllowMissing()
  @IsString()
  readonly minBackoff?: string;

  /**
   * The maximum backoff duration for task retries.
   */
  @AllowMissing()
  @IsString()
  readonly maxBackoff?: string;

  /**
   * The maximum number of times the backoff duration is doubled.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxDoublings?: number;

  [key: string]: any;
}

/**
 * The type of trigger.
 */
export enum ServiceContainerGoogleTaskTriggerType {
  GoogleTasks = 'google.tasks',
  Task = 'task',
}

/**
 * A trigger backed by a Google Cloud Tasks queue.
 */
export class ServiceContainerGoogleTaskTrigger {
  constructor(init: ServiceContainerGoogleTaskTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsIn(['google.tasks', 'task'])
  readonly type!: ServiceContainerGoogleTaskTriggerType;

  /**
   * The name of the queue for task triggers.
   */
  @IsString()
  readonly queue!: string;

  /**
   * The retry policy for the Cloud Tasks queue.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerGoogleTaskTriggerRetryPolicy)
  @ValidateNested()
  readonly retryPolicy?: ServiceContainerGoogleTaskTriggerRetryPolicy;

  [key: string]: any;
}

export class ServiceContainerOutputs {
  constructor(init: ServiceContainerOutputs) {
    Object.assign(this, init);
  }

  /**
   * The list of Firestore collections this service produces data into.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly 'google.firestore'?: string[];

  /**
   * The list of Spanner databases this service produces data into.
   * Each entry should be in the format `instance.database`.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly 'google.spanner'?: string[];

  [key: string]: any;
}

export type ServiceContainerPlatform = string | GoogleCloudRunPlatform;

export type TemplateString = string;

/**
 * Configuration for Cloud Run containers.
 */
export class GoogleCloudRun {
  constructor(init: GoogleCloudRun) {
    Object.assign(this, init);
  }

  /**
   * The Docker repository where Cloud Run containers should be uploaded.
   */
  @AllowMissing()
  @IsString()
  readonly dockerRepository?: string;

  /**
   * The location where Cloud Run services should be deployed.
   */
  @AllowMissing()
  @IsString()
  readonly location?: string;

  /**
   * For `serviceContainer` projects deployed on Cloud Run, the name of the Cloud Run service that receives
   * events during a backfill targeting a project-scoped trigger. Defaults to the project's name
   * (`project.name`) when unset.
   */
  @AllowMissing()
  @IsString()
  readonly eventBackfillServiceName?: string;

  /**
   * When set, project-scoped backfill triggers do not send events to the live Cloud Run service. Instead, a
   * temporary copy of the service is deployed for each trigger, isolating the backfill load (in particular its
   * scaling) from production. The copy is deleted once the backfill is cleaned up. Ingress is always
   * restricted to internal traffic for the copy. The properties of this object override the scaling settings
   * of the copied service. Unset properties are inherited from the live service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleCloudRunEventBackfillServiceCloneConfig)
  @ValidateNested()
  readonly eventBackfillServiceCloneConfig?: GoogleCloudRunEventBackfillServiceCloneConfig;

  /**
   * A map where keys are the name of environment variables, and values are secret versions IDs (e.g.
   * `projects/my-project/secrets/my-secret/versions/1`).
   */
  @AllowMissing()
  @IsObject()
  readonly secretEnvironmentVariables?: Record<string, TemplateString>;

  /**
   * Whether the container is running between requests and can perform background operations.
   */
  @AllowMissing()
  @IsBoolean()
  readonly cpuAlwaysAllocated?: boolean;

  /**
   * Whether to enable CPU boost during instance startup.
   */
  @AllowMissing()
  @IsBoolean()
  readonly startupCpuBoost?: boolean;

  /**
   * The max duration the instance is allowed for responding to a request, in seconds.
   */
  @AllowMissing()
  @IsNumber()
  readonly timeout?: number;

  /**
   * The maximum allowed in-flight (concurrent) requests per container.
   */
  @AllowMissing()
  @IsNumber()
  readonly requestConcurrency?: number;

  /**
   * The type of allowed ingress that can reach the container.
   * See https://cloud.google.com/run/docs/securing/ingress#settings for more details.
   */
  @AllowMissing()
  @IsIn(['all', 'internal', 'internal-and-cloud-load-balancing'])
  readonly ingress?: GoogleCloudRunIngress;

  /**
   * The name of the VPC access connector through which egress traffic should be routed.
   */
  @AllowMissing()
  @IsString()
  readonly vpcAccessConnector?: string;

  /**
   * The setting for egress traffic that goes through the VPC access connector.
   * See https://cloud.google.com/run/docs/configuring/connecting-vpc#manage for more details.
   */
  @AllowMissing()
  @IsIn(['ALL_TRAFFIC', 'PRIVATE_RANGES_ONLY'])
  readonly vpcAccessConnectorEgressSettings?: GoogleCloudRunVpcAccessConnectorEgressSettings;

  [key: string]: any;
}

/**
 * Configuration for everything Google / GCP-related.
 */
export class Google {
  constructor(init: Google) {
    Object.assign(this, init);
  }

  /**
   * The ID of the default GCP project used when performing operations.
   */
  @AllowMissing()
  @IsString()
  readonly project?: string;

  /**
   * The GCP region in which resource should be created and managed.
   */
  @AllowMissing()
  @IsString()
  readonly region?: string;

  /**
   * The ID of a local GCP project (which does not exist on GCP).
   * This is for example used by emulators. It should usually start with `demo-` to be compatible with some emulators.
   */
  @AllowMissing()
  @IsString()
  readonly localProject?: string;

  /**
   * The list of GCP services on which the project depends.
   * This is useful to automatically enable those services in the GCP project.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly services?: string[];

  /**
   * Configuration for the `gcloud` command.
   * This applies to Dockerized calls to `gcloud` using the official `gcloud` Docker image.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleGcloud)
  @ValidateNested()
  readonly gcloud?: GoogleGcloud;

  /**
   * Configuration for the Firebase project.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirebase)
  @ValidateNested()
  readonly firebase?: GoogleFirebase;

  /**
   * Configuration for the Secret Manager service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSecretManager)
  @ValidateNested()
  readonly secretManager?: GoogleSecretManager;

  /**
   * Configuration for the Firebase Storage service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirebaseStorage)
  @ValidateNested()
  readonly firebaseStorage?: GoogleFirebaseStorage;

  /**
   * Configuration for the Identity Platform (formerly Firebase Auth) service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleIdentityPlatform)
  @ValidateNested()
  readonly identityPlatform?: GoogleIdentityPlatform;

  /**
   * Configuration for the Firestore service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleFirestore)
  @ValidateNested()
  readonly firestore?: GoogleFirestore;

  /**
   * Configuration for the Pub/Sub service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GooglePubSub)
  @ValidateNested()
  readonly pubSub?: GooglePubSub;

  /**
   * Configuration for the Spanner service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleSpanner)
  @ValidateNested()
  readonly spanner?: GoogleSpanner;

  /**
   * Configuration for Cloud Functions.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleCloudFunctions)
  @ValidateNested()
  readonly cloudFunctions?: GoogleCloudFunctions;

  /**
   * Configuration for Cloud Run containers.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleCloudRun)
  @ValidateNested()
  readonly cloudRun?: GoogleCloudRun;

  /**
   * Default configuration for Cloud Scheduler jobs.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleScheduler)
  @ValidateNested()
  readonly scheduler?: GoogleScheduler;

  /**
   * Configuration for Google Cloud load balancing.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => GoogleLoadBalancing)
  @ValidateNested()
  readonly loadBalancing?: GoogleLoadBalancing;

  [key: string]: any;
}

/**
 * The schema for Google / GCP configuration.
 */
export class GoogleConfiguration {
  constructor(init: GoogleConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for everything Google / GCP-related.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Google)
  @ValidateNested()
  readonly google?: Google;

  [key: string]: any;
}

export type TemplateString_2 = string;

export class ServiceContainerGoogleEventarcTriggerFilter {
  constructor(init: ServiceContainerGoogleEventarcTriggerFilter) {
    Object.assign(this, init);
  }

  /**
   * The event attribute to filter on.
   */
  @IsString()
  readonly attribute!: string;

  /**
   * The value to match for the attribute.
   */
  @Allow()
  readonly value!: TemplateString_2;

  /**
   * The operator for matching the filter.
   */
  @AllowMissing()
  @IsString()
  readonly operator?: string;

  [key: string]: any;
}

/**
 * Google Eventarc-specific options for the trigger.
 */
export class ServiceContainerGoogleEventarcTriggerOptions {
  constructor(init: ServiceContainerGoogleEventarcTriggerOptions) {
    Object.assign(this, init);
  }

  /**
   * The content type of event data.
   */
  @IsString()
  readonly contentType!: string;

  /**
   * The location of the Eventarc trigger.
   */
  @AllowMissing()
  readonly location?: TemplateString_2;

  /**
   * The list of matching criteria for the Eventarc trigger.
   */
  @IsArray()
  @IsDefined()
  @IsObject({ each: true })
  @Type(() => ServiceContainerGoogleEventarcTriggerFilter)
  @ValidateNested()
  readonly filters!: ServiceContainerGoogleEventarcTriggerFilter[];

  [key: string]: any;
}

/**
 * A trigger backed by a Google Eventarc trigger.
 */
export class ServiceContainerGoogleEventarcTrigger {
  constructor(init: ServiceContainerGoogleEventarcTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsIn(['google.eventarc'])
  readonly type!: ServiceContainerGoogleEventarcTriggerType;

  /**
   * Google Eventarc-specific options for the trigger.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerGoogleEventarcTriggerOptions)
  @ValidateNested()
  readonly 'google.eventarc'?: ServiceContainerGoogleEventarcTriggerOptions;

  [key: string]: any;
}

export type ServiceContainerTrigger =
  | ServiceContainerGenericTrigger
  | ServiceContainerGooglePubSubTrigger
  | ServiceContainerGoogleSchedulerTrigger
  | ServiceContainerGoogleTaskTrigger
  | ServiceContainerGoogleEventarcTrigger;

export class GoogleServiceContainer {
  constructor(init: GoogleServiceContainer) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly platform?: ServiceContainerPlatform;

  /**
   * A map of triggers that call the service's endpoints when they occur.
   */
  @AllowMissing()
  @IsObject()
  readonly triggers?: Record<string, ServiceContainerTrigger>;

  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerOutputs)
  @ValidateNested()
  readonly outputs?: ServiceContainerOutputs;

  [key: string]: any;
}

/**
 * Google-specific extensions to the service container configuration.
 */
export class GoogleServiceContainerConfiguration {
  constructor(init: GoogleServiceContainerConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => GoogleServiceContainer)
  @ValidateNested()
  readonly serviceContainer?: GoogleServiceContainer;

  [key: string]: any;
}
